/**
 * DfuSe Memory Segment.
 * This is generated by parsing the DFU interface's `iInterface` or string descriptor.
 */
export type DfuSeMemorySegment = {
	start: number;
	end: number;
	sectorSize: number;

	readable: boolean;
	erasable: boolean;
	writable: boolean;
};
